version: "3.9"
services:
  jenkins:
    container_name: my-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "~/Desktop/Jenkins_home_desktop/workspace:/var/jenkins_home/workspace"
    image: "jenkins/jenkins:latest"
